### ISSUE TITLE
online version of docs would be nice

### ISSUE THREAD

**Issue by sr105** [alunduil/crumbs#20]
So people don't have to download and build them just to see if your project is worth downloading in the first place. Or at least some basic usage.

**Comment by alunduil** [comment]
Absolutely!  I'll work on adding a readthedocs output and a few other cleanups for this project over the next couple of weeks.  Is there anything in particular you'd like to see in the documentation?

**Comment by alunduil** [comment]
So I checked out the project again and I found that I do have online documentation available at https://crumbs.readthedocs.io/en/latest/.  I did spend a few pull requests trying to get this project updated but it's architecture is simply too old to be easily made modern.

My stance is that this shouldn't be used and I also am starting to think that argparse shouldn't be used either but I'll leave this available in case others are still finding it useful for their projects.

Otherwise, is there a simple way I could make the documentation more visible?  I'm guessing a link from the README would be helpful, but where did you look for documentation and find that none was available?

**Comment by sr105** [comment]
Thank you for responding. A link to that site in the readme where you have the `pydoc` line would be nice. A sample snippet of code showing usage would be good, too. When i found your project, i was looking for how others handled project configuration that could be set in different ways and could possibly be multi- layered, like inheritance.

**Comment by alunduil** [comment]
Excellent.  I'll get the README updates I had planned worked out and add the link to that documentation as part of it.  

If you want other examples of how I handle project configuration, you should check out my latest python project: https://github.com/alunduil/zfs-replicate.  It uses a modern toolset and follows the latest guidelines on setup.py vs requirements.txt.  Using direnv has made project work a lot easier to handle for me, but your mileage may vary.

If you have any specific questions about project configuration, let me know I'd be more than happy to have a discussion about various merits and share opinions.

**Comment by alunduil** [comment]
Alright, I've got some updates to the README in #25.  I'd love to get your take on it before merging.

**Comment by alunduil** [comment]
I've merged #25 so I'll mark this issue closed.  Thanks for the report and the check on sanity.  I'll get the new version published in the next week (tomorrow if I'm lucky).
